### ISSUE TITLE
using this package stops app from building

### ISSUE THREAD

**Issue by nszeitli** [skawa-universe/image_whisperer#3]
Couldnt find dart:htnl and then:

E/flutter ( 6721): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Dart_LoadScriptFromKernel: The binary program does not contain 'main'.
E/flutter ( 6721): [ERROR:flutter/shell/platform/android/android_shell_holder.cc(104)] Could not launch engine in configuration.

**Comment by gothamgasworks** [comment]
> Couldnt find dart:html and then:

> E/flutter

If I'm not mistaken, you're trying to use this package in a Flutter application, right?

This package was intended for the web, it does not support Flutter.
